events {}

http {
    server {
        listen 80;

        location /api/users/ {
            rewrite ^/api/users/(.*) /users/$1 break;
            proxy_pass http://user-service:8000;
        }

        location /api/games/ {
            rewrite ^/api/games/(.*) /games/$1 break;
            proxy_pass http://steam-service:8001;
        }
    }
}